### PR TITLE
Capture trivial paths in AllDirectedPaths

### LINKED ISSUE #198: AllDirectedPaths does not find paths of length 0 or 1
Like the title says, the AllDirectedPaths algorithm (introduced in PR #181) only finds directed paths of length 2 or longer (cf. test code below, searching for simple paths only gives similar results). While a workaround is rather simple to write, I don't think this should be the responsibilty of the application developer (finding paths is the algorithm's raison d'être, after all). I tested this with versions 0.9.2 (2432532a6642e27d99c8124a094751577a4df655) and c3adaefd5721b65b066ce4941ac09599eaf23dbd (HEAD of the master branch as I write this).

### Test code
```java
DirectedGraph<String, DefaultEdge> graph = new DefaultDirectedGraph<>(DefaultEdge.class);
graph.addVertex("source");
graph.addVertex("target1");
graph.addVertex("target2");
graph.addEdge("source", "target1");
graph.addEdge("target1", "target2"); // source --> target1 <-> target2
graph.addEdge("target2", "target1");
List<GraphPath<String, DefaultEdge>> paths = new AllDirectedPaths<>(graph).getAllPaths(
  new TreeSet<>(Arrays.asList("source", "target1", "target2")),
  new TreeSet<>(Arrays.asList("target1", "target2")),
  false, Integer.valueOf(3));
if (paths.size() != 9 && paths.size() != 11) {
  System.out.println("Unexpected number of paths: " + paths.size());
}
for (GraphPath<String, DefaultEdge> path: paths) {
  System.out.println(path);
}
```

### Expected output

<pre>[(target1)]
[(target2)]
[(source : target1)]
[(source : target1), (target1 : target2)]
[(source : target1), (target1 : target2), (target2 : target1)]
[(target2 : target1)]
[(target2 : target1), (target1 : target2)]
[(target2 : target1), (target1 : target2), (target2 : target1)]
[(target1 : target2)]
[(target1 : target2), (target2 : target1)]
[(target1 : target2), (target2 : target1), (target1 : target2)]
</pre>
<pre>[(source : target1)]
[(source : target1), (target1 : target2)]
[(source : target1), (target1 : target2), (target2 : target1)]
[(target2 : target1)]
[(target2 : target1), (target1 : target2)]
[(target2 : target1), (target1 : target2), (target2 : target1)]
[(target1 : target2)]
[(target1 : target2), (target2 : target1)]
[(target1 : target2), (target2 : target1), (target1 : target2)]
</pre>
or something similar (as long as there are 9 or 11 paths).

### Actual output

<pre>Unexpected number of paths: 6
[(source : target1), (target1 : target2)]
[(source : target1), (target1 : target2), (target2 : target1)]
[(target2 : target1), (target1 : target2)]
[(target2 : target1), (target1 : target2), (target2 : target1)]
[(target1 : target2), (target2 : target1)]
[(target1 : target2), (target2 : target1), (target1 : target2)]
</pre>

### PR DESCRIPTION
**Pull request by agdphd**
Correctly handle paths of length 0 and 1 in AllDirectedPaths algorithm. Fixes #198 and #234.

### CODE REVIEW

**Comment by jkinable** [comment]
Thanks for fixing this.
Would it be possible for you to add some additional information to the description of this algorithm, more specifically:
- is the implementation inspired by some book/paper etc? If so, please reference it.
- what's the runtime complexity of the algorithm?

This information is very valuable for people to understand your code, possibly improve your code, compare against alternative implementations, citing your work etc.

File: jgrapht-core/src/test/java/org/jgrapht/alg/AllDirectedPathsTest.java [hunk 1]
```diff
@@ -78,6 +78,24 @@ public void testSmallExampleGraph () {
...
+        sources.add(I1);
+
+        Set<String> targets = new HashSet<>();
+        targets.add(I1);
+        targets.add(A);
+
+        List<GraphPath<String, DefaultEdge>> allPaths =
+            pathFindingAlg.getAllPaths(sources, targets, true, null);
+
+        assertEquals("Toy network should have correct number of trivial simple paths", 2, allPaths.size());
```
Comment (jkinable) [inline jgrapht-core/src/test/java/org/jgrapht/alg/AllDirectedPathsTest.java]: Since there are only 2 paths, would it be a good idea to explicitly state them and compare with equals? That seems a bit more secure than simply checking the cardinality of the set of paths.

**Comment by jsichi** [comment]
Merging this now so we can have the fix available.  @agdphd if you can address @jkinable 's comments, please open another pull request for that.
