### PR TITLE
Fix bad mask checking in MaskEdgeSet.contains()

### LINKED ISSUE #160: Bug in MaskEdgeSet
[MaskEdgeSet](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/MaskEdgeSet.java) has inconsistent behaviour for contains() and iterator() methods. While first one returns false [only when mask.isEdgeMasked()](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/MaskEdgeSet.java#L87) returns true, iterator iterates correctly over edges that [are either explicitly masked or at least one of their ends is masked](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/MaskEdgeSet.java#L137).

Correct behaviour IMHO would be for contains to have the same check as iterator.

### PR DESCRIPTION
**Pull request by agdphd**
I think this fixes #160 (and thus possibly #182?), but more tests would be useful.

### CODE REVIEW

**Comment by agdphd** [comment]
While I was in there, I attempted to fix #161 as well.

File: jgrapht-core/src/main/java/org/jgrapht/graph/MaskEdgeSet.java [hunk 1]
```diff
@@ -77,8 +74,16 @@ public MaskEdgeSet(
      */
     @Override public boolean contains(Object o)
     {
-        return this.edgeSet.contains(o)
-            && !this.mask.isEdgeMasked(TypeUtil.uncheckedCast(o, edgeTypeDecl));
+        // Type system shenanigans to check whether o is an edge
+        try {
```
Comment (jsichi) [inline jgrapht-core/src/main/java/org/jgrapht/graph/MaskEdgeSet.java]: Are you sure this try/catch actually does anything useful?

File: jgrapht-core/src/test/java/org/jgrapht/graph/MaskEdgeSetTest.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+                @Override
+                public boolean isVertexMasked (String vertex) {
+                    return (vertex == v1);
+                }
+            };
+
+        testMaskedEdgeSet = new MaskEdgeSet<>(directed, directed.edgeSet(), mask);
+    }
+
+    // TESTS
```
Comment (jsichi) [inline jgrapht-core/src/test/java/org/jgrapht/graph/MaskEdgeSetTest.java]: No need for this comment.

File: jgrapht-core/src/main/java/org/jgrapht/graph/MaskEdgeSet.java (hunk 1 above)
Comment (agdphd) [inline jgrapht-core/src/main/java/org/jgrapht/graph/MaskEdgeSet.java]: Without it, this would throw a ClassCastException if contains() is called on something that isn't an E, which I think users would find surprising.

Unfortunately, I couldn't use the more legible "o instanceof E" because the generic type E is erased. I don't fully understand why this approach doesn't have the same problem, but that's Java for you.

**Comment by agdphd** [comment]
Oh, jeez, you're totally right about the try/cast/catch approach—it's totally useless because of erasure. Starting each contains() by checking whether the underlying set contains o should still do the job, though. (For example, in MaskVertexSet.contains(Object o), if o fails vertexSet.contains(o), it short-circuits the test and won't check mask.isVertexMasked(o).)
Updating my code now.

**Comment by jsichi** [comment]
Thanks.  As an optimization, it's possible to use a listener in MaskSubgraph to detect changes in the underlying graph; that way we could go back to caching the set sizes (or even more aggressive indexing).

But better to get correctness first and come back to performance later.
