### PR TITLE
Maximum Weight Bipartite Matching

### LINKED ISSUE #384: MaximumWeightBipartiteMatching behaves incorrectly for fractional weights
If edge weight is < 1 `MaximumWeightBipartiteMatching` drops first(?) edge from matching.

I believe it happens because of following cast:
https://github.com/jgrapht/jgrapht/blob/0f95bc63b501b4d521dd80412ba0add685ae617b/jgrapht-core/src/main/java/org/jgrapht/alg/matching/MaximumWeightBipartiteMatching.java#L120

It's very confusing because method `setEdgeWeight` accepts doubles:
https://github.com/jgrapht/jgrapht/blob/0f95bc63b501b4d521dd80412ba0add685ae617b/jgrapht-core/src/main/java/org/jgrapht/graph/AbstractBaseGraph.java#L497

### PR DESCRIPTION
**Pull request by d-michail**
Rewrote the algorithm for maximum weight bipartite matching (resolves #384). 

 - This is an improved implementation (again from the LEDA book) which computes shortest paths (on tight edges) based on a Fibonacci heap. Running time is O(n(m+n \log n)) where n is the number of vertices and m the number of edges.
 - The implementation uses exact arithmetic to always compute a maximum weight matching.
 - Added a Fibonacci heap variant which uses a custom key type with a `Comparator`.
 - Added tests which execute the algorithm on random instances and check for optimality using duality.

### CODE REVIEW

File: jgrapht-core/src/main/java/org/jgrapht/alg/matching/MaximumWeightBipartiteMatching.java [hunk 1]
```diff
@@ -17,39 +17,71 @@
...
+    private Map<V, BigDecimal> pot;
+    // the matched edge of a vertex, also used to check if a vertex is free
+    private Map<V, E> matchedEdge;
 
-    private Map<V, Long> vertexWeights;
-    private Map<V, Boolean> hasVertexBeenProcessed;
-    private Map<E, Boolean> isEdgeMatched;
+    // shortest path related data structures
+    private GenericFibonacciHeap<BigDecimal, V> heap;
+    private Set<V> isInHeap;
```
Comment (jsichi) [inline jgrapht-core/src/main/java/org/jgrapht/alg/matching/MaximumWeightBipartiteMatching.java]: Is it possible to use nodeInHeap to compute isInHeap as well (to avoid redundancy)?

File: jgrapht-core/src/main/java/org/jgrapht/alg/matching/MaximumWeightBipartiteMatching.java [hunk 2]
```diff
@@ -75,210 +102,286 @@ public MaximumWeightBipartiteMatching(Graph<V, E> graph, Set<V> partition1, Set<
...
+        return matchingWeight;
     }
 
-    private boolean isTargetVertex(V vertex)
+    /**
+     * Get the matching edges.
+     * 
+     * @return the matching edges
+     */
+    public Set<E> getMatchingEdges()
```
Comment (jsichi) [inline jgrapht-core/src/main/java/org/jgrapht/alg/matching/MaximumWeightBipartiteMatching.java]: I understand why you're exposing getPotentials (algorithm-specific result) and getMatchingWeight (exact BigDecimal instead of the double returned by the Matching interface), but isn't getMatchingEdges redundant with getMatching().getEdges()?

File: jgrapht-core/src/main/java/org/jgrapht/alg/matching/MaximumWeightBipartiteMatching.java (hunk 1 above)
Comment (d-michail) [reply jgrapht-core/src/main/java/org/jgrapht/alg/matching/MaximumWeightBipartiteMatching.java]: Indeed, nice suggestion.

**Comment by jsichi** [comment]
Merging, thanks!
