### PR TITLE
Fixes scc and undirected graphs issue

### LINKED ISSUE #674: StrongConnectivityInspector accepts undirected graphs
Currently `GraphTests.isStronglyConnected` as well as KosarajuStrongConnectivityInspector accept both directed and undirected graphs. When provided with an undirected graph, the implementation doesn't behave well. For instance, invoking `isStronglyConnected` on an undirected graph with 2 vertices and 1 edge returns false. 

Solutions (pick one)
1. Change Objects.requireNonNull to GraphTests.requireDirected to ensure that the StrongConnectivityInspector is only invoked on Directed Graphs
2. Although Strong Connectivity is usually described for Directed Graphs, the concept remains well-defined for undirected graphs (similar to outgoingEdgesOf(v)=incomingEdgesOf(v)=edgesOf(v)). So an undirected graph would be 'Strongly Connected' if it is connected. The strongly connected components equal the connected components. So if the Strong Connectivity Inspector is invoked on a undirected graph, we could delegate this to the Connectivity Inspector.

I'm fine with either solution.

### PR DESCRIPTION
**Pull request by d-michail**
Fixes #674. 

(and a few minor typos and type checking issues prior to the next release).

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

File: jgrapht-core/src/main/java/org/jgrapht/GraphTests.java [hunk 1]
```diff
@@ -260,7 +258,11 @@
     public static <V, E> boolean isStronglyConnected(Graph<V, E> graph)
     {
         Objects.requireNonNull(graph, GRAPH_CANNOT_BE_NULL);
-        return new KosarajuStrongConnectivityInspector<>(graph).isStronglyConnected();
+        if (graph.getType().isUndirected()) {
```
Comment (jkinable) [inline jgrapht-core/src/main/java/org/jgrapht/GraphTests.java]: The javadoc of this method requires updating too: directed graph -> graph. Moreover, I would specify explicitly that this method supports both directed and undirected graphs. 

Finally, `AbstractStrongConnectivityInspector` probably needs a requiredDirectedGraph instead of objectsNonNull

File: jgrapht-core/src/main/java/org/jgrapht/alg/color/BrownBacktrackColoring.java [hunk 2]
```diff
@@ -52,7 +51,6 @@
      */
     public BrownBacktrackColoring(Graph<V, E> graph)
     {
-        this.graph = Objects.requireNonNull(graph, "Graph cannot be null");
```
[the remark this answers is not in the document]
Comment (d-michail) [reply jgrapht-core/src/main/java/org/jgrapht/alg/color/BrownBacktrackColoring.java]: Oops

File: jgrapht-core/src/main/java/org/jgrapht/GraphTests.java (hunk 1 above)
Comment (d-michail) [reply jgrapht-core/src/main/java/org/jgrapht/GraphTests.java]: Improved the docs. The `AbstractStrongConnectivityInspector` change was already there.
