### PR TITLE
Fixed bug in JohnsonSimpleCycles with custom edge types

### LINKED ISSUE #474: JohnsonSimpleCycles throws IllegalArgumentException no such edge in graph
Hi,
I'm experimenting with `jgrapht` particularly with simple cycle finders.
In my particular setup, switching all `XSimpleCycles` algorithms works except Jonhson's, throwing:

```
[org.jgrapht.graph.BaseIntrusiveEdgesSpecifics getEdgeTarget "BaseIntrusiveEdgesSpecifics.java" 111]
[org.jgrapht.graph.AbstractBaseGraph getEdgeTarget "AbstractBaseGraph.java" 289]
[org.jgrapht.alg.cycle.JohnsonSimpleCycles findSimpleCycles "JohnsonSimpleCycles.java" 119]
```
I'm using a `DefaultDirectedWeightedGraph` with `DefaultWeightedEdge`. For the particular edge it reports, `g.getEdgeTarget` works if called manually. As vertices I'm using [this class](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/PersistentVector.java), where [`equals`](https://github.com/clojure/clojure/blob/ebfdbca535b81808b3ddc369d4a4e98b8f1524c7/src/jvm/clojure/lang/APersistentVector.java#L129) and [`hashCode`](https://github.com/clojure/clojure/blob/ebfdbca535b81808b3ddc369d4a4e98b8f1524c7/src/jvm/clojure/lang/APersistentVector.java#L141) are defined.

My wild guess, as I'm calling` jgrapht` from Clojure land, there might be something funny going on with generics but that seems highly unlikely since they are not a runtime concept.

### PR DESCRIPTION
**Pull request by d-michail**
The solution is to create new graphs using the original graph's edge factory. Fixes #474.

Update: 
I had the time to do a bit of cleaning up with the following changes: 
 - Cleaned up `JohnsonSimpleCycles` to use proper type checking
 - Fixed `JohnsonSimpleCycles` to return cycles in proper edge direction (instead of the reverse)
 - Removed `getGraph()` and `setGraph()` from the `DirectedSimpleCycles` interface.
 - Added one more test for `JohnsonSimpleCycles`.

### CODE REVIEW

**Comment by d-michail** [comment]
This PR also takes care of #337.

File: jgrapht-core/src/main/java/org/jgrapht/alg/cycle/JohnsonSimpleCycles.java [hunk 1]
```diff
@@ -161,12 +166,11 @@ public void setGraph(Graph<V, E> graph)
...
         }
         if (minSCC == null) {
-            return result;
+            return null;
         }
 
         // build a graph for the SCC found
-        Graph<V, E> resultGraph = new DefaultDirectedGraph<>(
-            new ClassBasedEdgeFactory<>((Class<? extends E>) DefaultEdge.class));
+        Graph<V, E> resultGraph = new DefaultDirectedGraph<>(graph.getEdgeFactory());
```
Comment (jsichi) [inline jgrapht-core/src/main/java/org/jgrapht/alg/cycle/JohnsonSimpleCycles.java]: After reviewing the place where we call addEdge on the result graph, I'm wondering why we don't reuse the edges from the original graph instead of creating new ones.  This would have the benefit that if the original graph was weighted (or had other edge attributes), those would be preserved on the cycles, whereas currently we will create uniform edges (e.g. all with weight 1).

Comment (d-michail) [reply jgrapht-core/src/main/java/org/jgrapht/alg/cycle/JohnsonSimpleCycles.java]: Nice catch, since the edges use the same source and target. I did the necessary changes. For now it does matter much since cycles are returned as list of vertices, however, I plan to augment the interface to also return a list of `GraphPath`s in the future.

I also added a check for "multiple" edges as the implementation does not support this.

**Comment by jsichi** [comment]
Thanks!
